Mig16.0 stock critical forecast link replenish
Mint-System/Odoo-Apps-Stock-Logistics-Workflow pull request #2
Opened 2024-06-24 15:32 UTC by laszlokr

@janikvonrotz the module is still not working correctly, this PR is work in progress

2024-06-24 15:48 UTC, janikvonrotz requested changes
I am missing the test instructions.

2024-06-24 15:50 UTC, laszlokr commented
@janikvonrotz yes, sorry, I will add the test instructions. I haven't made them because I could not verify it working

2024-06-24 15:52 UTC, janikvonrotz commented
@laszlokr 

> the module is still not working correctly, this PR is work in progress

You can set the PR to draft. I you ask for review I assume what I review is working.

2024-06-26 06:13 UTC, janikvonrotz requested changes

2024-06-26 06:13 UTC, janikvonrotz commented on stock_critical_forecast_link_replenish/tests/TEST_INSTRUCTIONS.rst
The tests desn't make sense.

The first step is unnecessary.

The product should be shown because of the orderpoint entry.

Please redo.

2024-06-26 06:56 UTC, closed without merging